Print old and new branch tips

diff --git a/git-rebase-all b/git-rebase-all
--- a/git-rebase-all
+++ b/git-rebase-all
@@ -76,10 +76,20 @@ else
   branches=${branches#merging }
 fi
 
+git update-ref refs/hidden/octomerge_rebased HEAD || die "update-ref failed"
+
+echo
+echo "Old branches tips:"
+git rev-parse refs/hidden/octomerge^@ | xargs -n1 git --no-pager log -1 --oneline --decorate
+echo
+echo "New rebased branches tips:"
+git rev-parse refs/hidden/octomerge_rebased^@ | xargs -n1 git --no-pager log -1 --oneline --decorate
+echo
+
 # Move all the old branches to point to the rebased commits.
 # The parents of the octomerge remain in the same order through the rebase.
 branches_list=($branches)
-new_commit_list=(`git rev-parse HEAD^@`)
+new_commit_list=(`git rev-parse refs/hidden/octomerge_rebased^@`)
 for index in ${!branches_list[@]}; do
   branch=${branches_list[$index]}
   echo "moving $branch (was $(git rev-parse --short $branch))"
@@ -89,3 +99,4 @@ done
 # and clean up.
 git checkout -q ${branches_list[0]}
 git update-ref -d refs/hidden/octomerge
+git update-ref -d refs/hidden/octomerge_rebased
