Support duplicated tips, add sanity checks and warnings

diff --git a/git-rebase-all b/git-rebase-all
--- a/git-rebase-all
+++ b/git-rebase-all
@@ -50,6 +50,10 @@ _git-rebase-all_octopus_merge() {
   [[ "${GIT_REBASE_ALL_DEBUG:-0}" -eq 0 ]] || set -x
   local branches="$*"
 
+  # Git already ignores "duplicated parents" (two branch on same commit), but
+  # with a warning. ! we must not sort !
+  local tips=$(git rev-parse $branches | awk '!a[$0]++')
+
   # Use the tree from the common ancestor of all the branches. It probably
   # doesn't matter what tree we use, but the merge-base is a) conveniently
   # accessible and b) probably the most sensible thing. Conceptually, this
@@ -61,7 +65,7 @@ _git-rebase-all_octopus_merge() {
   # Create the octomerge: a temporary commit that has all the topic branches as
   # parents.
   local octomerge=$(echo 'git-rebase-all-merging' $branches |
-                      git commit-tree $tree -p `echo $branches | sed -e's/ / -p /g'`)
+                      git commit-tree $tree -p `echo $tips | sed -e's/ / -p /g'`)
   echo "$octomerge"
 }
 # Make function available for rebase and rebase --continue
@@ -138,28 +142,57 @@ fi
 
 git update-ref refs/hidden/octomerge_rebased HEAD || die "update-ref failed"
 
-echo
-echo "Old branches tips:"
-git rev-parse refs/hidden/octomerge^@ | xargs -n1 git --no-pager log -1 --oneline --decorate
-echo
-echo "New rebased branches tips:"
-git rev-parse refs/hidden/octomerge_rebased^@ | xargs -n1 git --no-pager log -1 --oneline --decorate
-echo
-
-# Move all the old branches to point to the rebased commits.
 # The parents of the octomerge remain in the same order through the rebase.
-branches_list=($branches)
-new_commit_list=(`git rev-parse refs/hidden/octomerge_rebased^@`)
-if [[ "${#branches_list[@]}" -ne "${#new_commit_list[@]}" ]]; then
+old_tips=($(git rev-parse refs/hidden/octomerge^@))
+new_tips=($(git rev-parse refs/hidden/octomerge_rebased^@))
+if [[ "${#old_tips[@]}" -ne "${#new_tips[@]}" ]]; then
   die "rebased merge has been corrupted. aborting."
 fi
-for index in ${!branches_list[@]}; do
-  branch=${branches_list[$index]}
-  echo "moving $branch (was $(git rev-parse --short $branch))"
-  git branch -f $branch ${new_commit_list[$index]}
+
+git_pretty_tips() { for tip in "$@" ; do git --no-pager log -1 --oneline --decorate --color=always "$tip" ; done ; }
+echo "
+Old branches tips:
+$(git_pretty_tips "${old_tips[@]}")
+
+New rebased branches tips:
+$(git_pretty_tips "${new_tips[@]}")
+"
+
+git_log_small() { git log --abbrev=6 --format='%h %<(80,trunc)%s' "$@" ; }
+
+apply=()
+revert=()
+had_warnings=0
+for i in ${!old_tips[@]}; do
+  old_sha="${old_tips[$i]}"
+  new_sha="${new_tips[$i]}"
+
+  old_msg="$(git log --format='%s' -1 $old_sha)"
+  new_msg="$(git log --format='%s' -1 $new_sha)"
+  if [[ "$old_msg" != "$new_msg" ]]; then
+    echo "warning: old and rebased commit message does not match: ($old_sha) '$old_msg' ($new_sha) '$new_msg'" >&2
+    had_warning=1
+  fi
+
+  for branch in $(git for-each-ref --points-at=$old_sha --format='%(refname:strip=2)' refs/heads/ | \
+                    grep --fixed-string --line-regexp -f <(printf '%s\n' $branches) )
+  do
+    apply+=("git branch -f $branch $new_sha")
+    revert+=("git branch -f $branch $old_sha")
+  done
+done
+
+echo "Note: to revert, in case of failure:
+$(printf '%s\n' "${revert[@]}")
+"
+
+echo "Now applying:"
+for app in "${apply[@]}" ; do
+  echo "$app"
+  eval "$app" || die "branch failed, see above to revert"
 done
 
 # and clean up.
-git checkout -q ${branches_list[0]}
+git checkout -q ${branches%% *}
 git update-ref -d refs/hidden/octomerge
 git update-ref -d refs/hidden/octomerge_rebased
